services:
  user-service:
    build: .
    container_name: user-service
    environment:
      - PORT=3001
      - SERVICE_NAME=USER
      - MONGO_URL=mongodb://mongo:27017/userdb
    ports:
      - "3001:3001"
    command: ["node", "server.js"]

  product-service:
    build: .
    container_name: product-service
    environment:
      - PORT=3002
      - SERVICE_NAME=PRODUCT
      - MONGO_URL=mongodb://mongo:27017/productdb
    ports:
      - "3002:3002"
    command: ["node", "server.js"]

  order-service:
    build: .
    container_name: order-service
    environment:
      - PORT=3003
      - SERVICE_NAME=ORDER
      - MONGO_URL=mongodb://mongo:27017/orderdb
    ports:
      - "3003:3003"
    command: ["node", "server.js"]

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
