global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3002']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3003']

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "my_app"
    static_configs:
      - targets: ["my_app:3000"]

  - job_name: "mongo"
    static_configs:
      - targets: ["mongo-exporter:9216"]  # MongoDB exporter container

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alert-rules.yml"
