apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentcourseapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentcourseapp
  template:
    metadata:
      labels:
        app: studentcourseapp
    spec:
      containers:
      - name: studentcourseapp
        image: studentcourseapp:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
